export const latestPosterSchedule = [
  {
    month: 'April',
    locations: 'Bengaluru, Karnataka',
    baseLocation: 'Other',
    appointment: false,
    maxPeople: 0,
    publicTitle: {
      en: 'Hindu Dharma Acharya Sabha Adhiveshan',
      hi: 'हिन्दू धर्म आचार्य सभा अधिवेशन',
    },
    publicLocation: {
      en: 'Bengaluru, Karnataka',
      hi: 'बेंगलुरु (कर्नाटक)',
    },
    publicNotes: {
      en: 'Poster schedule entry from 02 April evening to 05 April morning 2026.',
      hi: 'पोस्टर के अनुसार 02 अप्रैल सायं से 05 अप्रैल प्रातः 2026 तक का कार्यक्रम।',
    },
    internalNotes: 'Seeded from April–June 2026 poster. Venue line should be verified once with staff.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-04-02T18:00:00.000Z'),
        endDate: new Date('2026-04-05T06:00:00.000Z'),
        period: 'whole day',
      },
    ],
  },
  {
    month: 'April',
    locations: 'Delhi Ashram, New Delhi',
    baseLocation: 'Delhi Ashram',
    appointment: true,
    maxPeople: 25,
    publicTitle: { en: 'Delhi Darshan & Meetings', hi: 'दिल्ली दर्शन एवं मुलाकात' },
    publicLocation: { en: 'Delhi Ashram, New Delhi', hi: 'दिल्ली आश्रम, नई दिल्ली' },
    publicNotes: {
      en: 'Appointments require prior approval from the seva team.',
      hi: 'मुलाकात हेतु पूर्व स्वीकृति आवश्यक है।',
    },
    internalNotes: 'Poster entry dated 06 April 2026. Good candidate for appointment testing.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-04-06T06:00:00.000Z'),
        endDate: new Date('2026-04-06T18:00:00.000Z'),
        period: 'whole day',
        slotCapacity: 25,
      },
    ],
  },
  {
    month: 'April',
    locations: 'Harihar Ashram & Bharat Mata Mandir, Haridwar',
    baseLocation: 'Haridwar Ashram',
    appointment: true,
    maxPeople: 25,
    publicTitle: {
      en: 'Harihar Ashram Darshan Window',
      hi: 'हरिहर आश्रम दर्शन अवधि',
    },
    publicLocation: {
      en: 'Harihar Ashram & Bharat Mata Mandir, Haridwar',
      hi: 'हरिहर आश्रम एवं भारत माता मंदिर, हरिद्वार',
    },
    publicNotes: {
      en: 'Devotee meetings are subject to prior approval and time allocation.',
      hi: 'भक्तों की मुलाकात पूर्व स्वीकृति और निर्धारित समय पर ही संभव है।',
    },
    internalNotes: 'Poster entry 07 April to 11 April 2026.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-04-07T06:00:00.000Z'),
        endDate: new Date('2026-04-11T18:00:00.000Z'),
        period: 'whole day',
        slotCapacity: 25,
      },
    ],
  },
  {
    month: 'April',
    locations: 'Lucknow, Uttar Pradesh',
    baseLocation: 'Other',
    appointment: false,
    maxPeople: 0,
    publicTitle: { en: 'Lucknow Visit', hi: 'लखनऊ प्रवास' },
    publicLocation: { en: 'Lucknow, Uttar Pradesh', hi: 'लखनऊ (उत्तरप्रदेश)' },
    publicNotes: {
      en: 'Poster entry from 12 April evening to 13 April noon 2026.',
      hi: 'पोस्टर के अनुसार 12 अप्रैल सायं से 13 अप्रैल दोपहर 2026 तक का कार्यक्रम।',
    },
    internalNotes: 'Short programme window from the poster.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-04-12T18:00:00.000Z'),
        endDate: new Date('2026-04-13T12:00:00.000Z'),
        period: 'whole day',
      },
    ],
  },
  {
    month: 'April',
    locations: 'Harihar Ashram & Bharat Mata Mandir, Haridwar',
    baseLocation: 'Haridwar Ashram',
    appointment: true,
    maxPeople: 25,
    publicTitle: { en: 'Haridwar Ashram Stay', hi: 'हरिद्वार आश्रम प्रवास' },
    publicLocation: {
      en: 'Harihar Ashram & Bharat Mata Mandir, Haridwar',
      hi: 'हरिहर आश्रम एवं भारत माता मंदिर, हरिद्वार',
    },
    publicNotes: {
      en: 'Appointments remain subject to prior team approval.',
      hi: 'मुलाकात पूर्व टीम स्वीकृति के अनुसार ही होगी।',
    },
    internalNotes: 'Poster entry 13 April evening to 19 April 2026.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-04-13T18:00:00.000Z'),
        endDate: new Date('2026-04-19T18:00:00.000Z'),
        period: 'whole day',
        slotCapacity: 25,
      },
    ],
  },
  {
    month: 'April',
    locations: 'Omkareshwar, Khandwa District, Madhya Pradesh',
    baseLocation: 'Other',
    appointment: false,
    maxPeople: 0,
    publicTitle: {
      en: 'Bhagavatpada Madhavacharya Jayanti Programme',
      hi: 'भगवत्पादाचार्य माधवाचार्य जयंती कार्यक्रम',
    },
    publicLocation: {
      en: 'Omkareshwar, Khandwa District, Madhya Pradesh',
      hi: 'ओंकारेश्वर, जिला-खंडवा (मध्य प्रदेश)',
    },
    publicNotes: {
      en: 'Poster entry from 20 April evening to 22 April morning 2026.',
      hi: 'पोस्टर के अनुसार 20 अप्रैल सायं से 22 अप्रैल प्रातः 2026 तक का कार्यक्रम।',
    },
    internalNotes: 'Seeded from poster text. Verify exact event title spelling with staff.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-04-20T18:00:00.000Z'),
        endDate: new Date('2026-04-22T06:00:00.000Z'),
        period: 'whole day',
      },
    ],
  },
  {
    month: 'April',
    locations: 'Nagpur, Maharashtra',
    baseLocation: 'Other',
    appointment: false,
    maxPeople: 0,
    publicTitle: { en: 'Nagpur Visit', hi: 'नागपुर प्रवास' },
    publicLocation: { en: 'Nagpur, Maharashtra', hi: 'नागपुर' },
    publicNotes: {
      en: 'Poster entry from 23 April to 25 April afternoon 2026.',
      hi: 'पोस्टर के अनुसार 23 अप्रैल से 25 अप्रैल दोपहर 2026 तक का कार्यक्रम।',
    },
    internalNotes: 'Poster includes local contact numbers for Nagpur.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-04-23T06:00:00.000Z'),
        endDate: new Date('2026-04-25T12:00:00.000Z'),
        period: 'whole day',
      },
    ],
  },
  {
    month: 'April',
    locations: 'Bhubaneswar, Odisha',
    baseLocation: 'Other',
    appointment: false,
    maxPeople: 0,
    publicTitle: { en: 'Bhubaneswar Visit', hi: 'भुवनेश्वर प्रवास' },
    publicLocation: { en: 'Bhubaneswar, Odisha', hi: 'भुवनेश्वर (ओडिशा)' },
    publicNotes: {
      en: 'Poster entry dated 26 April 2026.',
      hi: 'पोस्टर के अनुसार 26 अप्रैल 2026 का कार्यक्रम।',
    },
    internalNotes: 'Single-day visit.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-04-26T06:00:00.000Z'),
        endDate: new Date('2026-04-26T18:00:00.000Z'),
        period: 'whole day',
      },
    ],
  },
  {
    month: 'April',
    locations: 'Harihar Ashram & Bharat Mata Mandir, Haridwar',
    baseLocation: 'Haridwar Ashram',
    appointment: true,
    maxPeople: 25,
    publicTitle: { en: 'Haridwar Return Window', hi: 'हरिद्वार वापसी अवधि' },
    publicLocation: {
      en: 'Harihar Ashram & Bharat Mata Mandir, Haridwar',
      hi: 'हरिहर आश्रम एवं भारत माता मंदिर, हरिद्वार',
    },
    publicNotes: {
      en: 'Appointments require prior approval.',
      hi: 'मुलाकात हेतु पूर्व स्वीकृति आवश्यक है।',
    },
    internalNotes: 'Poster entry 28 April to 29 April 2026.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-04-28T06:00:00.000Z'),
        endDate: new Date('2026-04-29T18:00:00.000Z'),
        period: 'whole day',
        slotCapacity: 25,
      },
    ],
  },
  {
    month: 'April',
    locations: 'District Jail, Ghaziabad, Uttar Pradesh',
    baseLocation: 'Other',
    appointment: false,
    maxPeople: 0,
    publicTitle: {
      en: 'Navagrah Vatika & Library Establishment Programme',
      hi: 'नवग्रह वाटिका एवं पुस्तकालय स्थापना कार्यक्रम',
    },
    publicLocation: {
      en: 'District Jail, Ghaziabad, Uttar Pradesh',
      hi: 'जिला कारागार, गाजियाबाद (उत्तर प्रदेश)',
    },
    publicNotes: {
      en: 'Poster entry dated 30 April 2026.',
      hi: 'पोस्टर के अनुसार 30 अप्रैल 2026 का कार्यक्रम।',
    },
    internalNotes: 'Poster text appears to mention Gandhi-related jail/library installation. Verify exact Hindi title with staff.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-04-30T06:00:00.000Z'),
        endDate: new Date('2026-04-30T18:00:00.000Z'),
        period: 'whole day',
      },
    ],
  },
  {
    month: 'May',
    locations: 'Sydney, Australia',
    baseLocation: 'Other',
    appointment: false,
    maxPeople: 0,
    publicTitle: { en: 'Sydney Visit', hi: 'सिडनी प्रवास' },
    publicLocation: { en: 'Sydney, Australia', hi: 'सिडनी (ऑस्ट्रेलिया)' },
    publicNotes: {
      en: 'Poster entry from 01 May evening to 08 May 2026.',
      hi: 'पोस्टर के अनुसार 01 मई सायं से 08 मई 2026 तक का कार्यक्रम।',
    },
    internalNotes: 'Poster includes Sydney local contact details.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-05-01T18:00:00.000Z'),
        endDate: new Date('2026-05-08T18:00:00.000Z'),
        period: 'whole day',
      },
    ],
  },
  {
    month: 'May',
    locations: 'Delhi Ashram, New Delhi',
    baseLocation: 'Delhi Ashram',
    appointment: true,
    maxPeople: 25,
    publicTitle: { en: 'Delhi Meetings', hi: 'दिल्ली मुलाकात' },
    publicLocation: { en: 'Delhi Ashram, New Delhi', hi: 'दिल्ली आश्रम, नई दिल्ली' },
    publicNotes: {
      en: 'Appointments subject to prior approval and confirmed timing.',
      hi: 'मुलाकात पूर्व स्वीकृति और निर्धारित समय के अनुसार होगी।',
    },
    internalNotes: 'Poster entry dated 09 May 2026.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-05-09T06:00:00.000Z'),
        endDate: new Date('2026-05-09T18:00:00.000Z'),
        period: 'whole day',
        slotCapacity: 25,
      },
    ],
  },
  {
    month: 'May',
    locations: 'Different Places',
    baseLocation: 'Other',
    appointment: false,
    maxPeople: 0,
    publicTitle: { en: 'Different Places', hi: 'विविध प्रवास' },
    publicLocation: { en: 'Different Places', hi: 'विविध प्रवास' },
    publicNotes: {
      en: 'Poster entry from 10 May to 14 May 2026.',
      hi: 'पोस्टर के अनुसार 10 मई से 14 मई 2026 तक विविध प्रवास।',
    },
    internalNotes: 'Travel block from poster.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-05-10T06:00:00.000Z'),
        endDate: new Date('2026-05-14T18:00:00.000Z'),
        period: 'whole day',
      },
    ],
  },
  {
    month: 'May',
    locations: 'Harihar Ashram, Kankhal, Haridwar',
    baseLocation: 'Haridwar Ashram',
    appointment: true,
    maxPeople: 25,
    publicTitle: {
      en: 'Adhik Maas Anushthan',
      hi: 'अधिक मास (पुरुषोत्तम मास) अनुष्ठान',
    },
    publicLocation: {
      en: 'Harihar Ashram, Kankhal, Haridwar',
      hi: 'हरिहर आश्रम, कनखल, हरिद्वार',
    },
    publicNotes: {
      en: 'Poster block runs 15 May to 17 June 2026. Main anushthan line mentions 17 May to 15 June; verify exact ceremonial span with staff.',
      hi: 'पोस्टर ब्लॉक 15 मई से 17 जून 2026 तक है। मुख्य अनुष्ठान पंक्ति 17 मई से 15 जून दर्शाती है, कृपया स्टाफ से पुष्टि करें।',
    },
    internalNotes: 'Long Haridwar base period from latest schedule poster.',
    isLastMinuteUpdate: false,
    isDeleted: false,
    timeSlots: [
      {
        startDate: new Date('2026-05-15T06:00:00.000Z'),
        endDate: new Date('2026-06-17T18:00:00.000Z'),
        period: 'whole day',
        slotCapacity: 25,
      },
    ],
  },
] as const;
